---
# - hosts: webserver
#   gather_facts: no
#   tasks: 
#     - name: This is my first task
#       file:
#         path: "{{ my_demo_folder_path }}"
#         state: directory
#         owner: ec2-user

#     - name: Creating a new file
#       file: 
#         path: "{{ my_demo_folder_path }}/new_file.txt"
#         state: touch
        
  
- hosts: all
  become: yes
  vars:
    server_name: "34.245.96.221"
    document_root: /var/www/html
    app_root: html_demo_site-main
  tasks:

    # - name: Enable amazon-linux-extras packages
    #   shell: "amazon-linux-extras enable nginx1" 


    - name: Update apt cache and install Nginx
      yum:
        name: nginx
        state: latest
        update_cache: yes

       

    - name: Copy website files to the server's document root
      copy:
        src: "{{ app_root }}"
        dest: "{{ document_root }}"
        mode: preserve


    - name: Apply Nginx template
      template:
        src: templates/default.j2
        dest: /etc/nginx/sites-available/default
      notify: Restart Nginx

    - name: Copy config files to the nginx default folder
      copy:
        src: files/nginx.conf
        dest: /etc/nginx/

    - name: Enable new site
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Restart Nginx


    # - name: Allow all access to tcp port 80
    #   ufw:
    #     rule: allow
    #     port: '80'
    #     proto: tcp

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
    # - name: Deleting a new file
    #   file: 
    #     path: "/home/ec2-user/my_new_folder/new_file.txt"
    #     state: absent